title: GSA Manager
description: GSA Manager is an associational and club management application.
show_downloads: true
google_analytics:
remote_theme: pages-themes/tactile@v0.2.0

github:
  zip_url: http://example.com/download.zip
  another_url: another value

plugins:
- jekyll-remote-theme